In [131]:
# !pip install chromadb

In [132]:
import pandas as pd

In [133]:
df = pd.read_csv('./card_card.csv')

In [134]:
# df['card_in_out_3'].unique()
df.drop(['card_in_out_1', 'card_in_out_2', 'card_in_out_3', 'card_img', 'card_overseas'], axis=1, inplace=True)

In [135]:
df['card_record'].unique()

array(['전월실적 없음', '전월실적20 만원 이상', '전월실적30 만원 이상', '전월실적50 만원 이상',
       '전월실적10 만원 이상', '전월실적40 만원 이상', '전월실적15 만원 이상', '전월실적100 만원 이상',
       nan, '전월실적25 만원 이상', '전월실적5 만원 이상', '전월실적24 만원 이상', '전월실적8 만원 이상',
       '전월실적150 만원 이상', '전월실적75 만원 이상', '전월실적60 만원 이상', '전월실적200 만원 이상',
       '전월실적1 만원 이상', '전월실적70 만원 이상', '전월실적18 만원 이상', '전월실적29 만원 이상'],
      dtype=object)

In [136]:
# df[df['card_record'] == '전월실적1 만원 이상']

In [137]:
# df[df['card_record'].isna()]

In [138]:
df['card_record'] = df['card_record'].str.extract('(\d+)')

In [139]:
df['card_record'].fillna(0, inplace=True)

In [140]:
df['card_record'].unique()

array([0, '20', '30', '50', '10', '40', '15', '100', '25', '5', '24', '8',
       '150', '75', '60', '200', '1', '70', '18', '29'], dtype=object)

In [141]:
cardList = df
cardList

id            card_name card_brand card_record
0        1        신한카드 Hi-Point       신한카드           0
1        2            신한카드 Love       신한카드          20
2        3            신한카드 Lady       신한카드          30
3        4    SK에너지 신한카드The you       신한카드          30
4        5  GS칼텍스 신한카드Dream 100       신한카드          30
...    ...                  ...        ...         ...
2380  2381           삼프로TV 하나카드       하나카드          30
2381  2382  SC제일은행-현대카드 M CHECK       현대카드           0
2382  2383  SC제일은행-현대카드 X CHECK       현대카드           0
2383  2384     네이버페이 머니 하나 체크카드       하나카드          25
2384  2385          네이버페이 쇼핑엔로카       롯데카드           0

[2385 rows x 4 columns]

In [142]:
cardList.dropna(subset=['card_name'], inplace=True)

In [143]:
cardList['card_name'].isna().unique()

array([False])

## 카드 혜택 분석

In [144]:
df = pd.read_csv('./card_benefit.csv')

In [145]:
print(df['card_id'].value_counts())

1010    18
1022    17
85      17
1228    17
1027    16
        ..
194      1
195      1
196      1
2170     1
1896     1
Name: card_id, Length: 2337, dtype: int64


In [146]:
grouped = df[['bnf_detail', 'card_id']]
grouped = grouped.set_index('card_id', drop=True)
# type(grouped)
grouped['bnf_detail']

card_id
1       롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목...
1       전국 가맹점 0.2~2.0% 적립\n- 국내 어디서나 이용한 일시불/할부 금액의 0...
1       S-OIL / 현대오일뱅크 주유 시 리터 당 60원 마이신한포인트 적립\n- S-O...
1       신한투자증권 CMA 결제계좌 지정 시 신판이용 금액의 0.2% 마이신한포인트 추가 ...
1       SK텔레콤/KT/LG U+ 이동통신요금 1.0~5.0% 적립\n- SK텔레콤/KT/...
                              ...                        
2384    네이버페이 포인트 적립 서비스 세부 사항\n- 적립된 포인트는 네이버페이 사이트에서...
2385    네이버페이 포인트 적립서비스\n구분 지난달(1일 ~ 말일) 네이버페이 쇼핑엔로카 카...
2385    장기할부 서비스\n장기할부 조건\n할부개월수 할부요율(연) 할부 이용액 상환방식\n...
2385                                                  NaN
2385    장기할부 이용 시\n- 서비스 제공횟수는 장기할부 이용 기간에 따라 12개월(12회...
Name: bnf_detail, Length: 13753, dtype: object

In [147]:
grouped['bnf_detail'].fillna('', inplace=True)
grouped['bnf_detail'].isna().unique()

array([False])

In [148]:
grouped = grouped.groupby(level=0).agg(' '.join)
grouped['bnf_detail']

card_id
1       롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목...
2       국내 유명 백화점, 할인점, 온라인 쇼핑몰 최대 5% 할인\n- 백화점 : 현대, ...
3       3대 백화점(롯데, 신세계, 현대) 및 롯데마트 5% 결제일 할인\n- 월 2회 통...
4       전국 SK 주유소에서 주유 시 리터당 100원 할인\n- SK 주유시 전월 신판(일...
5       전국 GS칼텍스 주유 시 리터당 100원 할인\n- 주유 할인 한도 : 월 50만원...
                              ...                        
2381    특화서비스 청구할인\n구분 할인 대상 할인율 월 할인한도 지난달 실적\n삼프로TV ...
2382    M포인트 적립\n- 전월 이용 금액 100만원 미만 시 0.5%, 100만원 이상 ...
2383    X캐시백 적립\n- 전월 이용 금액 100만원 미만 시 0.3%, 100만원 이상 ...
2384    네이버페이 포인트 적립 서비스\n- 적립 대상: 국내/외 모든 가맹점\n- 적립률:...
2385    네이버페이 포인트 적립서비스\n구분 지난달(1일 ~ 말일) 네이버페이 쇼핑엔로카 카...
Name: bnf_detail, Length: 2337, dtype: object

In [149]:
# print(grouped.loc[1, 'bnf_detail'])

In [150]:
grouped = grouped.reset_index()
grouped.columns = ['id', 'bnf_detail']
grouped

id                                         bnf_detail
0        1  롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목...
1        2  국내 유명 백화점, 할인점, 온라인 쇼핑몰 최대 5% 할인\n- 백화점 : 현대, ...
2        3  3대 백화점(롯데, 신세계, 현대) 및 롯데마트 5% 결제일 할인\n- 월 2회 통...
3        4  전국 SK 주유소에서 주유 시 리터당 100원 할인\n- SK 주유시 전월 신판(일...
4        5  전국 GS칼텍스 주유 시 리터당 100원 할인\n- 주유 할인 한도 : 월 50만원...
...    ...                                                ...
2332  2381  특화서비스 청구할인\n구분 할인 대상 할인율 월 할인한도 지난달 실적\n삼프로TV ...
2333  2382  M포인트 적립\n- 전월 이용 금액 100만원 미만 시 0.5%, 100만원 이상 ...
2334  2383  X캐시백 적립\n- 전월 이용 금액 100만원 미만 시 0.3%, 100만원 이상 ...
2335  2384  네이버페이 포인트 적립 서비스\n- 적립 대상: 국내/외 모든 가맹점\n- 적립률:...
2336  2385  네이버페이 포인트 적립서비스\n구분 지난달(1일 ~ 말일) 네이버페이 쇼핑엔로카 카...

[2337 rows x 2 columns]

In [152]:
cardList = pd.merge(cardList, grouped, how='inner')

In [153]:
cardList

id            card_name card_brand card_record  \
0        1        신한카드 Hi-Point       신한카드           0   
1        2            신한카드 Love       신한카드          20   
2        3            신한카드 Lady       신한카드          30   
3        4    SK에너지 신한카드The you       신한카드          30   
4        5  GS칼텍스 신한카드Dream 100       신한카드          30   
...    ...                  ...        ...         ...   
2331  2381           삼프로TV 하나카드       하나카드          30   
2332  2382  SC제일은행-현대카드 M CHECK       현대카드           0   
2333  2383  SC제일은행-현대카드 X CHECK       현대카드           0   
2334  2384     네이버페이 머니 하나 체크카드       하나카드          25   
2335  2385          네이버페이 쇼핑엔로카       롯데카드           0   

                                             bnf_detail  
0     롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목...  
1     국내 유명 백화점, 할인점, 온라인 쇼핑몰 최대 5% 할인\n- 백화점 : 현대, ...  
2     3대 백화점(롯데, 신세계, 현대) 및 롯데마트 5% 결제일 할인\n- 월 2회 통...  
3     전국 SK 주유소에서 주유 시 리터당 100원 할인\n- SK 주유시 전월 신판(일...  
4     전국 GS칼텍스 주유 시 리터당 100원 할인\n- 주유 할인 한도 : 월 50만원...  
...                                                 ...  
2331  특화서비스 청구할인\n구분 할인 대상 할인율 월 할인한도 지난달 실적\n삼프로TV ...  
2332  M포인트 적립\n- 전월 이용 금액 100만원 미만 시 0.5%, 100만원 이상 ...  
2333  X캐시백 적립\n- 전월 이용 금액 100만원 미만 시 0.3%, 100만원 이상 ...  
2334  네이버페이 포인트 적립 서비스\n- 적립 대상: 국내/외 모든 가맹점\n- 적립률:...  
2335  네이버페이 포인트 적립서비스\n구분 지난달(1일 ~ 말일) 네이버페이 쇼핑엔로카 카...  

[2336 rows x 5 columns]

In [168]:
print(cardList[cardList['card_name'].str.contains('신한카드 23')])

   id   card_name card_brand card_record  \
6   7  신한카드 23.5°       신한카드           0   

                                          bnf_detail  
6  생활 친화 가맹점 포인트 1% 포인트 적립\n- 전월 이용 금액 조건 상관 없이 1...  


In [154]:
# cardList[cardList['card_name'].str.contains('신한')]
cardList['card_name'].isna().unique()

array([False])

In [155]:
count = 0
for index, row in cardList.iterrows():
    count += len(row['bnf_detail'].split())
print(count)

1942671


In [156]:
train_data = []

for index, row in cardList.iterrows():
    train_data.append({
        "messages" : [
            {"role" : "system",
            "content" : "카드 혜택 안내"},
            {"role" : "user",
            "content" : str(row['card_name']) + "의 혜택은?"},
            {"role" : "assistant",
            "content" : row['bnf_detail']},
        ]
    })
    if index == 10: break

In [157]:
train_data

[{'messages': [{'role': 'system', 'content': '카드 혜택 안내'},
   {'role': 'user', 'content': '신한카드 Hi-Point의 혜택은?'},
   {'role': 'assistant',
    'content': '롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목 및 온라인매장은 적립 제외\n- 세일기간, 식품매장에서도 적립 서비스 제공\n\n롯데마트/이마트/홈플러스/토이저러스 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목 및 온라인 매장은 적립 제외\n- 롯데슈퍼/이마트에브리데이/이마트메트로/홈플러스익스프레스 등 할인점 계열, 슈퍼마켓(SSM)은 특별적립 대상 제외\n\nCJ오쇼핑/CJmall 마이신한포인트 1.0~5.0% 적립\n- 상품권 구매건 제외(0.2~2.0% 적립률 적용) 전국 가맹점 0.2~2.0% 적립\n- 국내 어디서나 이용한 일시불/할부 금액의 0.2~2.0% 마이신한포인트 적립\n  * 1.0~5.0% 적립처, 60원/ℓ 적립처를 제외한 전국 모든 가맹점을 대상으로 함.\n  * 지방세 및 선불충전형카드(기프트카드 등) 적립제외\n\n해외 가맹점 1.0~5.0% 마이신한포인트 적립\n- 해외가맹점 일시불/할부 이용금액에 대하여 1.0~5.0% 마이신한포인트 적립 S-OIL / 현대오일뱅크 주유 시 리터 당 60원 마이신한포인트 적립\n- S-OIL/현대오일뱅크 리터 당 60원 적립\n- 적립포인트 산정방법 = 주유이용금액 × 리터당 적립금액(60원) / 기준유가\n  * 기준유가 : S-OIL/현대오일뱅크가 통보한 휘발유가입니다.\n- S-OIL/현대오일뱅크 정유사별 월 2회, 주유금액 20만원까지 적립\n- 주유금액 20만원 월한도 초과시 다음 결제건부터 0.2~2.0% 적립처와 동일한 포인트 적립\n- 정유사가 통보한 휘발유 표준 고시유가 기준\n  * LPG 충전소 제외, 경유·등유는 휘발유가로 계산되어 적립됩니다. 신한투자증권 CMA

In [ ]:
import json
# JSON 문자열 파싱
# data = json.loads(train_data)
# JSONL 형식으로 출력
with open("train_data.jsonl", "w", encoding='utf8') as file:
    for item in train_data:
        file.write(json.dumps(item) + "\n")

In [55]:
# We start by importing the required packages

import json
import os
import tiktoken
import numpy as np
from collections import defaultdict

# Next, we specify the data path and open the JSONL file

data_path = "train_data.jsonl"

# Load dataset
with open(data_path) as f:
    dataset = [json.loads(line) for line in f]

# We can inspect the data quickly by checking the number of examples and the first item

# Initial dataset stats
print("Num examples:", len(dataset))
print("First example:")
for message in dataset[0]['messages']:
    print(message)

# Now that we have a sense of the data, we need to go through all the different examples and check to make sure the formatting is correct and matches the Chat completions message structure

# Format error checks
format_errors = defaultdict(int)

for ex in dataset:
    if not isinstance(ex, dict):
        format_errors["data_type"] += 1
        continue

    messages = ex.get("messages", None)
    if not messages:
        format_errors["missing_messages_list"] += 1
        continue

    for message in messages:
        if "role" not in message or "content" not in message:
            format_errors["message_missing_key"] += 1

        if any(k not in ("role", "content", "name") for k in message):
            format_errors["message_unrecognized_key"] += 1

        if message.get("role", None) not in ("system", "user", "assistant"):
            format_errors["unrecognized_role"] += 1

        content = message.get("content", None)
        if not content or not isinstance(content, str):
            format_errors["missing_content"] += 1

    if not any(message.get("role", None) == "assistant" for message in messages):
        format_errors["example_missing_assistant_message"] += 1

if format_errors:
    print("Found errors:")
    for k, v in format_errors.items():
        print(f"{k}: {v}")
else:
    print("No errors found")

# Beyond the structure of the message, we also need to ensure that the length does not exceed the 4096 token limit.

# Token counting functions
encoding = tiktoken.get_encoding("cl100k_base")
# encoding = tiktoken.get_encoding("UTF-8")

# not exact!
# simplified from https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
def num_tokens_from_messages(messages, tokens_per_message=3, tokens_per_name=1):
    num_tokens = 0
    for message in messages:
        num_tokens += tokens_per_message
        for key, value in message.items():
            num_tokens += len(encoding.encode(value))
            if key == "name":
                num_tokens += tokens_per_name
    num_tokens += 3
    return num_tokens

def num_assistant_tokens_from_messages(messages):
    num_tokens = 0
    for message in messages:
        if message["role"] == "assistant":
            num_tokens += len(encoding.encode(message["content"]))
    return num_tokens

def print_distribution(values, name):
    print(f"\n#### Distribution of {name}:")
    print(f"min / max: {min(values)}, {max(values)}")
    print(f"mean / median: {np.mean(values)}, {np.median(values)}")
    print(f"p5 / p95: {np.quantile(values, 0.1)}, {np.quantile(values, 0.9)}")

# Last, we can look at the results of the different formatting operations before proceeding with creating a fine-tuning job:

# Warnings and tokens counts
n_missing_system = 0
n_missing_user = 0
n_messages = []
convo_lens = []
assistant_message_lens = []

for ex in dataset:
    messages = ex["messages"]
    if not any(message["role"] == "system" for message in messages):
        n_missing_system += 1
    if not any(message["role"] == "user" for message in messages):
        n_missing_user += 1
    n_messages.append(len(messages))
    convo_lens.append(num_tokens_from_messages(messages))
    assistant_message_lens.append(num_assistant_tokens_from_messages(messages))

print("Num examples missing system message:", n_missing_system)
print("Num examples missing user message:", n_missing_user)
print_distribution(n_messages, "num_messages_per_example")
print_distribution(convo_lens, "num_total_tokens_per_example")
print_distribution(assistant_message_lens, "num_assistant_tokens_per_example")
n_too_long = sum(l > 4096 for l in convo_lens)
print(f"\n{n_too_long} examples may be over the 4096 token limit, they will be truncated during fine-tuning")
print('convo_lens', convo_lens)

# Pricing and default n_epochs estimate
MAX_TOKENS_PER_EXAMPLE = 4096

MIN_TARGET_EXAMPLES = 100
MAX_TARGET_EXAMPLES = 25000
TARGET_EPOCHS = 1
MIN_EPOCHS = 1
MAX_EPOCHS = 25

n_epochs = TARGET_EPOCHS
n_train_examples = len(dataset)
if n_train_examples * TARGET_EPOCHS < MIN_TARGET_EXAMPLES:
    n_epochs = min(MAX_EPOCHS, MIN_TARGET_EXAMPLES // n_train_examples)
elif n_train_examples * TARGET_EPOCHS > MAX_TARGET_EXAMPLES:
    n_epochs = max(MIN_EPOCHS, MAX_TARGET_EXAMPLES // n_train_examples)

n_billing_tokens_in_dataset = sum(min(MAX_TOKENS_PER_EXAMPLE, length) for length in convo_lens)
print(f"Dataset has ~{n_billing_tokens_in_dataset} tokens that will be charged for during training")
print(f"By default, you'll train for {n_epochs} epochs on this dataset")
print(f"By default, you'll be charged for ~{n_epochs * n_billing_tokens_in_dataset} tokens")
print("See pricing page to estimate total costs")

Num examples: 11
First example:
{'role': 'system', 'content': '카드 혜택 안내'}
{'role': 'user', 'content': '신한카드 Hi-Point의 혜택은?'}
{'role': 'assistant', 'content': '롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목 및 온라인매장은 적립 제외\n- 세일기간, 식품매장에서도 적립 서비스 제공\n\n롯데마트/이마트/홈플러스/토이저러스 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목 및 온라인 매장은 적립 제외\n- 롯데슈퍼/이마트에브리데이/이마트메트로/홈플러스익스프레스 등 할인점 계열, 슈퍼마켓(SSM)은 특별적립 대상 제외\n\nCJ오쇼핑/CJmall 마이신한포인트 1.0~5.0% 적립\n- 상품권 구매건 제외(0.2~2.0% 적립률 적용) 전국 가맹점 0.2~2.0% 적립\n- 국내 어디서나 이용한 일시불/할부 금액의 0.2~2.0% 마이신한포인트 적립\n  * 1.0~5.0% 적립처, 60원/ℓ 적립처를 제외한 전국 모든 가맹점을 대상으로 함.\n  * 지방세 및 선불충전형카드(기프트카드 등) 적립제외\n\n해외 가맹점 1.0~5.0% 마이신한포인트 적립\n- 해외가맹점 일시불/할부 이용금액에 대하여 1.0~5.0% 마이신한포인트 적립 S-OIL / 현대오일뱅크 주유 시 리터 당 60원 마이신한포인트 적립\n- S-OIL/현대오일뱅크 리터 당 60원 적립\n- 적립포인트 산정방법 = 주유이용금액 × 리터당 적립금액(60원) / 기준유가\n  * 기준유가 : S-OIL/현대오일뱅크가 통보한 휘발유가입니다.\n- S-OIL/현대오일뱅크 정유사별 월 2회, 주유금액 20만원까지 적립\n- 주유금액 20만원 월한도 초과시 다음 결제건부터 0.2~2.0% 적립처와 동일한 포인트 적립\n- 정유사가 통보한 휘발유 표준 고시유가 기준\n  * LPG 충전소 제외, 경유·등유는 휘발유가로 계산되어 적립됩니다. 신한투자증

## 파인튜닝

In [57]:
import openai
import os
openai.api_key = "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"

openai.File.create(
  file=open("train_data.jsonl", "rb"),
  purpose='fine-tune'
)

<File file id=file-YBut9OSoYpmTJErugIMh7dGX at 0x26611ad3110> JSON: {
  "object": "file",
  "id": "file-YBut9OSoYpmTJErugIMh7dGX",
  "purpose": "fine-tune",
  "filename": "file",
  "bytes": 182195,
  "created_at": 1693553606,
  "status": "uploaded",
  "status_details": null
}

In [58]:
openai.FineTuningJob.create(training_file="file-YBut9OSoYpmTJErugIMh7dGX", model="gpt-3.5-turbo")

<FineTuningJob fine_tuning.job id=ftjob-rP8Y8gieBbjplstFe0VCT6CG at 0x26611ad2b70> JSON: {
  "object": "fine_tuning.job",
  "id": "ftjob-rP8Y8gieBbjplstFe0VCT6CG",
  "model": "gpt-3.5-turbo-0613",
  "created_at": 1693553679,
  "finished_at": null,
  "fine_tuned_model": null,
  "organization_id": "org-gGJUUFkRdru1nE1itsRt9p6C",
  "result_files": [],
  "status": "created",
  "validation_file": null,
  "training_file": "file-YBut9OSoYpmTJErugIMh7dGX",
  "hyperparameters": {
    "n_epochs": 9
  },
  "trained_tokens": null
}

In [61]:
# Retrieve the state of a fine-tune
openai.FineTuningJob.retrieve("ftjob-rP8Y8gieBbjplstFe0VCT6CG")

<FineTuningJob fine_tuning.job id=ftjob-rP8Y8gieBbjplstFe0VCT6CG at 0x2660f176b10> JSON: {
  "object": "fine_tuning.job",
  "id": "ftjob-rP8Y8gieBbjplstFe0VCT6CG",
  "model": "gpt-3.5-turbo-0613",
  "created_at": 1693553679,
  "finished_at": 1693554269,
  "fine_tuned_model": "ft:gpt-3.5-turbo-0613:personal::7tt7OKAm",
  "organization_id": "org-gGJUUFkRdru1nE1itsRt9p6C",
  "result_files": [
    "file-QSTLxvPl8WZiEImIrv0TCBhb"
  ],
  "status": "succeeded",
  "validation_file": null,
  "training_file": "file-YBut9OSoYpmTJErugIMh7dGX",
  "hyperparameters": {
    "n_epochs": 9
  },
  "trained_tokens": 328023
}

In [62]:
# 테스트
completion = openai.ChatCompletion.create(
  model="ft:gpt-3.5-turbo-0613:personal::7tt7OKAm",
  messages=[
    {"role": "user", "content": "Hello!"}
  ]
)

print(completion.choices[0].message)

{
  "role": "assistant",
  "content": "Hello! How can I assist you today?"
}


In [63]:
train_data

[{'messages': [{'role': 'system', 'content': '카드 혜택 안내'},
   {'role': 'user', 'content': '신한카드 Hi-Point의 혜택은?'},
   {'role': 'assistant',
    'content': '롯데/ 현대백화점 마이신한포인트 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목 및 온라인매장은 적립 제외\n- 세일기간, 식품매장에서도 적립 서비스 제공\n\n롯데마트/이마트/홈플러스/토이저러스 1.0~5.0% 적립\n- 문화센타 등 비쇼핑 항목 및 온라인 매장은 적립 제외\n- 롯데슈퍼/이마트에브리데이/이마트메트로/홈플러스익스프레스 등 할인점 계열, 슈퍼마켓(SSM)은 특별적립 대상 제외\n\nCJ오쇼핑/CJmall 마이신한포인트 1.0~5.0% 적립\n- 상품권 구매건 제외(0.2~2.0% 적립률 적용) 전국 가맹점 0.2~2.0% 적립\n- 국내 어디서나 이용한 일시불/할부 금액의 0.2~2.0% 마이신한포인트 적립\n  * 1.0~5.0% 적립처, 60원/ℓ 적립처를 제외한 전국 모든 가맹점을 대상으로 함.\n  * 지방세 및 선불충전형카드(기프트카드 등) 적립제외\n\n해외 가맹점 1.0~5.0% 마이신한포인트 적립\n- 해외가맹점 일시불/할부 이용금액에 대하여 1.0~5.0% 마이신한포인트 적립 S-OIL / 현대오일뱅크 주유 시 리터 당 60원 마이신한포인트 적립\n- S-OIL/현대오일뱅크 리터 당 60원 적립\n- 적립포인트 산정방법 = 주유이용금액 × 리터당 적립금액(60원) / 기준유가\n  * 기준유가 : S-OIL/현대오일뱅크가 통보한 휘발유가입니다.\n- S-OIL/현대오일뱅크 정유사별 월 2회, 주유금액 20만원까지 적립\n- 주유금액 20만원 월한도 초과시 다음 결제건부터 0.2~2.0% 적립처와 동일한 포인트 적립\n- 정유사가 통보한 휘발유 표준 고시유가 기준\n  * LPG 충전소 제외, 경유·등유는 휘발유가로 계산되어 적립됩니다. 신한투자증권 CMA

In [21]:
import chromadb

In [22]:
client = chromadb.PersistentClient(path="../data")

In [23]:
collection = client.get_or_create_collection(
    name="test"
)

In [24]:
# 데이터 준비
# 인덱스
ids = []
# 메타데이터
doc_meta = []
# 벡터로 변환 저장할 텍스트 데이터로 ChromaDB에 Embedding 데이터가 없으면 자동으로 벡터로 변환해서 저장한다고 한다. 
documents = []